### ISSUE TITLE
How do we add a supprt for new locale?

### ISSUE THREAD

**Issue by JohnSiluvai** [Brightspace/intl#10]
For example:
If we need to support cy-GB UK (Scottish). How do we add this locale?

**Comment by dlockhart** [comment]
Hi John -- this library handles i18n within our company's product (Brightspace), so it currently only contains the locale data for the locales our product supports.

If you're just interested in doing basic Intl stuff in the browser, I'd recommend either using the [native JavaScript Intl stuff](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl), and/or supplementing with [this great polyfill](https://github.com/andyearnshaw/Intl.js/), which supports much of the same things our library does, and [may have the locale you're looking for](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/cy-GB.json)!
